name: Deploy Website

on:
  push:
    branches: [ main ]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    environment: Test

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
        
deploy-prod:
  runs-on: ubuntu-latest
  environment: Production
  needs: [deploy-test]