name: Deploy Website

on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOSTTEST }}
        username: ${{ secrets.USERNAMETEST }}
        password: ${{ secrets.PASSWORDTEST }}
        port: ${{ secrets.PORT }}
        script: |
          cd /var/www/html
          sudo -rm index.html
          git clone https://github.com/Y3llowm4n/ss_website.git